### ISSUE TITLE
Delivery Environment

### ISSUE THREAD

**Issue by JohnRoux** [neolikotsi/laravel-smsportal#4]
Hey,

It's a little odd ad very counter-intuitive that by default config, this will send smses on all environments _except_ production

I was going to make a PR, but there are two main options here:

1) Simple: Have a single env variable which is just an enabled flag: `(SMS_PORTAL_DELIVERY_ENABLED, true)`
It wouldn't care what environment you're on, it's configurable and very easily understood

2) Environment aware: Have an array in the config with they key/val being environment/bool. The implementation then looks at app env, finds the key in the array based on the env and looks up it's enabled state.

Option 2 would mean the least impact for users and by default we can disable sending sms's out on testing environments etc
But it would be a bit more prone to issues (if someone has an environment outside the norms, it would give a key error etc)

Thoughts?

**Comment by neolikotsi** [comment]
The idea is for the package to send actual SMSes only in **production** env. 
I like option 1 better. I'll merge that one.

**Comment by JohnRoux** [comment]
Can we push a new tag for this change?

**Comment by neolikotsi** [comment]
Yes. I was going to push a breaking change version tag (2.0.0). I'll push
it tonight (C.A.T)
